name: Staging Auto Deployment

on:
  push:
    branches:
      - "main"

jobs:
  Deploy-to-Main:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into server and perform git operations
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.CONSULTANCY }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd /var/www/redorangeconsultancy/
            bash auto_deploy.bash
